interface Emoji {
  emoji: string;
  name: string;
  keywords: string[];
  category: string;
}

const emojis: Emoji[] = [
  // Smileys & Emotion
  {
    emoji: "😀",
    name: "grinning face",
    keywords: ["happy", "smile", "grin"],
    category: "smileys",
  },
  {
    emoji: "😃",
    name: "grinning face with big eyes",
    keywords: ["happy", "smile", "joy"],
    category: "smileys",
  },
  {
    emoji: "😄",
    name: "grinning face with smiling eyes",
    keywords: ["happy", "smile", "laugh"],
    category: "smileys",
  },
  {
    emoji: "😁",
    name: "beaming face with smiling eyes",
    keywords: ["happy", "smile", "laugh"],
    category: "smileys",
  },
  {
    emoji: "😆",
    name: "grinning squinting face",
    keywords: ["laugh", "happy", "smile"],
    category: "smileys",
  },
  {
    emoji: "😅",
    name: "grinning face with sweat",
    keywords: ["laugh", "nervous", "sweat"],
    category: "smileys",
  },
  {
    emoji: "🤣",
    name: "rolling on the floor laughing",
    keywords: ["laugh", "rofl", "funny"],
    category: "smileys",
  },
  {
    emoji: "😂",
    name: "face with tears of joy",
    keywords: ["laugh", "cry", "funny"],
    category: "smileys",
  },
  {
    emoji: "🙂",
    name: "slightly smiling face",
    keywords: ["smile", "happy"],
    category: "smileys",
  },
  {
    emoji: "🙃",
    name: "upside-down face",
    keywords: ["silly", "sarcastic"],
    category: "smileys",
  },
  {
    emoji: "😊",
    name: "smiling face with smiling eyes",
    keywords: ["happy", "smile", "blush"],
    category: "smileys",
  },
  {
    emoji: "😇",
    name: "smiling face with halo",
    keywords: ["angel", "innocent"],
    category: "smileys",
  },
  {
    emoji: "🥰",
    name: "smiling face with hearts",
    keywords: ["love", "happy", "heart"],
    category: "smileys",
  },
  {
    emoji: "😍",
    name: "smiling face with heart-eyes",
    keywords: ["love", "heart", "eyes"],
    category: "smileys",
  },
  {
    emoji: "🤩",
    name: "star-struck",
    keywords: ["star", "eyes", "excited"],
    category: "smileys",
  },
  {
    emoji: "😘",
    name: "face blowing a kiss",
    keywords: ["kiss", "love"],
    category: "smileys",
  },
  {
    emoji: "😗",
    name: "kissing face",
    keywords: ["kiss", "lips"],
    category: "smileys",
  },
  {
    emoji: "☺️",
    name: "smiling face",
    keywords: ["happy", "smile"],
    category: "smileys",
  },
  {
    emoji: "😚",
    name: "kissing face with closed eyes",
    keywords: ["kiss", "closed", "eyes"],
    category: "smileys",
  },
  {
    emoji: "😙",
    name: "kissing face with smiling eyes",
    keywords: ["kiss", "smile"],
    category: "smileys",
  },
  {
    emoji: "🥲",
    name: "smiling face with tear",
    keywords: ["sad", "happy", "tear"],
    category: "smileys",
  },
  {
    emoji: "😋",
    name: "face savoring food",
    keywords: ["yum", "delicious", "tongue"],
    category: "smileys",
  },
  {
    emoji: "😛",
    name: "face with tongue",
    keywords: ["tongue", "silly"],
    category: "smileys",
  },
  {
    emoji: "😜",
    name: "winking face with tongue",
    keywords: ["wink", "tongue", "silly"],
    category: "smileys",
  },
  {
    emoji: "🤪",
    name: "zany face",
    keywords: ["crazy", "silly", "wild"],
    category: "smileys",
  },
  {
    emoji: "😝",
    name: "squinting face with tongue",
    keywords: ["tongue", "silly", "squint"],
    category: "smileys",
  },
  {
    emoji: "🤑",
    name: "money-mouth face",
    keywords: ["money", "rich", "dollar"],
    category: "smileys",
  },
  {
    emoji: "🤗",
    name: "smiling face with open hands",
    keywords: ["hug", "hands", "open"],
    category: "smileys",
  },
  {
    emoji: "🤭",
    name: "face with hand over mouth",
    keywords: ["oops", "surprise", "hand"],
    category: "smileys",
  },
  {
    emoji: "🤫",
    name: "shushing face",
    keywords: ["quiet", "shh", "secret"],
    category: "smileys",
  },
  {
    emoji: "🤔",
    name: "thinking face",
    keywords: ["think", "hmm", "consider"],
    category: "smileys",
  },
  {
    emoji: "🤐",
    name: "zipper-mouth face",
    keywords: ["quiet", "zip", "silence"],
    category: "smileys",
  },
  {
    emoji: "🤨",
    name: "face with raised eyebrow",
    keywords: ["suspicious", "eyebrow"],
    category: "smileys",
  },
  {
    emoji: "😐",
    name: "neutral face",
    keywords: ["neutral", "meh"],
    category: "smileys",
  },
  {
    emoji: "😑",
    name: "expressionless face",
    keywords: ["blank", "expressionless"],
    category: "smileys",
  },
  {
    emoji: "😶",
    name: "face without mouth",
    keywords: ["silent", "no", "mouth"],
    category: "smileys",
  },
  {
    emoji: "😏",
    name: "smirking face",
    keywords: ["smirk", "sly"],
    category: "smileys",
  },
  {
    emoji: "😒",
    name: "unamused face",
    keywords: ["unamused", "meh"],
    category: "smileys",
  },
  {
    emoji: "🙄",
    name: "face with rolling eyes",
    keywords: ["eye", "roll", "annoyed"],
    category: "smileys",
  },
  {
    emoji: "😬",
    name: "grimacing face",
    keywords: ["grimace", "awkward"],
    category: "smileys",
  },
  {
    emoji: "🤥",
    name: "lying face",
    keywords: ["lie", "pinocchio", "nose"],
    category: "smileys",
  },
  {
    emoji: "😔",
    name: "pensive face",
    keywords: ["sad", "pensive"],
    category: "smileys",
  },
  {
    emoji: "😪",
    name: "sleepy face",
    keywords: ["sleepy", "tired", "sleep"],
    category: "smileys",
  },
  {
    emoji: "🤤",
    name: "drooling face",
    keywords: ["drool", "hungry"],
    category: "smileys",
  },
  {
    emoji: "😴",
    name: "sleeping face",
    keywords: ["sleep", "zzz"],
    category: "smileys",
  },
  {
    emoji: "😷",
    name: "face with medical mask",
    keywords: ["mask", "sick", "medical"],
    category: "smileys",
  },
  {
    emoji: "🤒",
    name: "face with thermometer",
    keywords: ["sick", "fever", "thermometer"],
    category: "smileys",
  },
  {
    emoji: "🤕",
    name: "face with head-bandage",
    keywords: ["hurt", "bandage", "injured"],
    category: "smileys",
  },
  {
    emoji: "🤢",
    name: "nauseated face",
    keywords: ["sick", "nausea", "green"],
    category: "smileys",
  },
  {
    emoji: "🤮",
    name: "face vomiting",
    keywords: ["vomit", "sick"],
    category: "smileys",
  },
  {
    emoji: "🤧",
    name: "sneezing face",
    keywords: ["sneeze", "tissue"],
    category: "smileys",
  },
  {
    emoji: "🥵",
    name: "hot face",
    keywords: ["hot", "heat", "sweat"],
    category: "smileys",
  },
  {
    emoji: "🥶",
    name: "cold face",
    keywords: ["cold", "freeze", "blue"],
    category: "smileys",
  },
  {
    emoji: "🥴",
    name: "woozy face",
    keywords: ["dizzy", "drunk", "woozy"],
    category: "smileys",
  },
  {
    emoji: "😵",
    name: "face with crossed-out eyes",
    keywords: ["dead", "knocked", "out"],
    category: "smileys",
  },
  {
    emoji: "🤯",
    name: "exploding head",
    keywords: ["mind", "blown", "explode"],
    category: "smileys",
  },
  {
    emoji: "🤠",
    name: "cowboy hat face",
    keywords: ["cowboy", "hat", "western"],
    category: "smileys",
  },
  {
    emoji: "🥳",
    name: "partying face",
    keywords: ["party", "celebration", "hat"],
    category: "smileys",
  },
  {
    emoji: "🥸",
    name: "disguised face",
    keywords: ["disguise", "glasses", "mustache"],
    category: "smileys",
  },
  {
    emoji: "😎",
    name: "smiling face with sunglasses",
    keywords: ["cool", "sunglasses", "awesome"],
    category: "smileys",
  },
  {
    emoji: "🤓",
    name: "nerd face",
    keywords: ["nerd", "geek", "glasses"],
    category: "smileys",
  },
  {
    emoji: "🧐",
    name: "face with monocle",
    keywords: ["monocle", "fancy", "classy"],
    category: "smileys",
  },

  // People & Body
  {
    emoji: "👋",
    name: "waving hand",
    keywords: ["wave", "hello", "goodbye"],
    category: "people",
  },
  {
    emoji: "🤚",
    name: "raised back of hand",
    keywords: ["hand", "back", "stop"],
    category: "people",
  },
  {
    emoji: "🖐️",
    name: "hand with fingers splayed",
    keywords: ["hand", "fingers", "palm"],
    category: "people",
  },
  {
    emoji: "✋",
    name: "raised hand",
    keywords: ["hand", "high", "five"],
    category: "people",
  },
  {
    emoji: "🖖",
    name: "vulcan salute",
    keywords: ["spock", "vulcan", "star", "trek"],
    category: "people",
  },
  {
    emoji: "👌",
    name: "OK hand",
    keywords: ["ok", "okay", "perfect"],
    category: "people",
  },
  {
    emoji: "🤌",
    name: "pinched fingers",
    keywords: ["italian", "chef", "kiss"],
    category: "people",
  },
  {
    emoji: "🤏",
    name: "pinching hand",
    keywords: ["small", "tiny", "pinch"],
    category: "people",
  },
  {
    emoji: "✌️",
    name: "victory hand",
    keywords: ["peace", "victory", "two"],
    category: "people",
  },
  {
    emoji: "🤞",
    name: "crossed fingers",
    keywords: ["cross", "fingers", "luck"],
    category: "people",
  },
  {
    emoji: "🤟",
    name: "love-you gesture",
    keywords: ["love", "you", "rock"],
    category: "people",
  },
  {
    emoji: "🤘",
    name: "sign of the horns",
    keywords: ["rock", "metal", "horns"],
    category: "people",
  },
  {
    emoji: "🤙",
    name: "call me hand",
    keywords: ["call", "phone", "hang", "loose"],
    category: "people",
  },
  {
    emoji: "👈",
    name: "backhand index pointing left",
    keywords: ["point", "left"],
    category: "people",
  },
  {
    emoji: "👉",
    name: "backhand index pointing right",
    keywords: ["point", "right"],
    category: "people",
  },
  {
    emoji: "👆",
    name: "backhand index pointing up",
    keywords: ["point", "up"],
    category: "people",
  },
  {
    emoji: "🖕",
    name: "middle finger",
    keywords: ["middle", "finger", "rude"],
    category: "people",
  },
  {
    emoji: "👇",
    name: "backhand index pointing down",
    keywords: ["point", "down"],
    category: "people",
  },
  {
    emoji: "☝️",
    name: "index pointing up",
    keywords: ["point", "up", "one"],
    category: "people",
  },
  {
    emoji: "👍",
    name: "thumbs up",
    keywords: ["thumb", "up", "good", "yes"],
    category: "people",
  },
  {
    emoji: "👎",
    name: "thumbs down",
    keywords: ["thumb", "down", "bad", "no"],
    category: "people",
  },
  {
    emoji: "✊",
    name: "raised fist",
    keywords: ["fist", "power", "solidarity"],
    category: "people",
  },
  {
    emoji: "👊",
    name: "oncoming fist",
    keywords: ["fist", "bump", "punch"],
    category: "people",
  },
  {
    emoji: "🤛",
    name: "left-facing fist",
    keywords: ["fist", "left"],
    category: "people",
  },
  {
    emoji: "🤜",
    name: "right-facing fist",
    keywords: ["fist", "right"],
    category: "people",
  },
  {
    emoji: "👏",
    name: "clapping hands",
    keywords: ["clap", "applause", "bravo"],
    category: "people",
  },
  {
    emoji: "🙌",
    name: "raising hands",
    keywords: ["raise", "hands", "celebration"],
    category: "people",
  },
  {
    emoji: "👐",
    name: "open hands",
    keywords: ["open", "hands", "hug"],
    category: "people",
  },
  {
    emoji: "🤲",
    name: "palms up together",
    keywords: ["pray", "please", "palms"],
    category: "people",
  },
  {
    emoji: "🤝",
    name: "handshake",
    keywords: ["handshake", "deal", "agreement"],
    category: "people",
  },
  {
    emoji: "🙏",
    name: "folded hands",
    keywords: ["pray", "thanks", "please"],
    category: "people",
  },

  // Animals & Nature
  {
    emoji: "🐶",
    name: "dog face",
    keywords: ["dog", "puppy", "pet"],
    category: "animals",
  },
  {
    emoji: "🐱",
    name: "cat face",
    keywords: ["cat", "kitten", "pet"],
    category: "animals",
  },
  {
    emoji: "🐭",
    name: "mouse face",
    keywords: ["mouse", "rodent"],
    category: "animals",
  },
  {
    emoji: "🐹",
    name: "hamster",
    keywords: ["hamster", "pet"],
    category: "animals",
  },
  {
    emoji: "🐰",
    name: "rabbit face",
    keywords: ["rabbit", "bunny"],
    category: "animals",
  },
  { emoji: "🦊", name: "fox", keywords: ["fox", "sly"], category: "animals" },
  { emoji: "🐻", name: "bear", keywords: ["bear"], category: "animals" },
  {
    emoji: "🐼",
    name: "panda",
    keywords: ["panda", "bear"],
    category: "animals",
  },
  {
    emoji: "🐨",
    name: "koala",
    keywords: ["koala", "bear"],
    category: "animals",
  },
  {
    emoji: "🐯",
    name: "tiger face",
    keywords: ["tiger", "cat"],
    category: "animals",
  },
  {
    emoji: "🦁",
    name: "lion",
    keywords: ["lion", "king"],
    category: "animals",
  },
  {
    emoji: "🐮",
    name: "cow face",
    keywords: ["cow", "moo"],
    category: "animals",
  },
  {
    emoji: "🐷",
    name: "pig face",
    keywords: ["pig", "oink"],
    category: "animals",
  },
  {
    emoji: "🐽",
    name: "pig nose",
    keywords: ["pig", "nose"],
    category: "animals",
  },
  {
    emoji: "🐸",
    name: "frog",
    keywords: ["frog", "ribbit"],
    category: "animals",
  },
  {
    emoji: "🐵",
    name: "monkey face",
    keywords: ["monkey", "ape"],
    category: "animals",
  },
  {
    emoji: "🙈",
    name: "see-no-evil monkey",
    keywords: ["monkey", "see", "no", "evil"],
    category: "animals",
  },
  {
    emoji: "🙉",
    name: "hear-no-evil monkey",
    keywords: ["monkey", "hear", "no", "evil"],
    category: "animals",
  },
  {
    emoji: "🙊",
    name: "speak-no-evil monkey",
    keywords: ["monkey", "speak", "no", "evil"],
    category: "animals",
  },
  { emoji: "🐒", name: "monkey", keywords: ["monkey"], category: "animals" },
  {
    emoji: "🐔",
    name: "chicken",
    keywords: ["chicken", "rooster"],
    category: "animals",
  },
  { emoji: "🐧", name: "penguin", keywords: ["penguin"], category: "animals" },
  { emoji: "🐦", name: "bird", keywords: ["bird"], category: "animals" },
  {
    emoji: "🐤",
    name: "baby chick",
    keywords: ["chick", "baby", "bird"],
    category: "animals",
  },
  {
    emoji: "🐣",
    name: "hatching chick",
    keywords: ["chick", "hatching", "egg"],
    category: "animals",
  },
  {
    emoji: "🐥",
    name: "front-facing baby chick",
    keywords: ["chick", "baby"],
    category: "animals",
  },
  {
    emoji: "🦆",
    name: "duck",
    keywords: ["duck", "quack"],
    category: "animals",
  },
  {
    emoji: "🦅",
    name: "eagle",
    keywords: ["eagle", "bird"],
    category: "animals",
  },
  { emoji: "🦉", name: "owl", keywords: ["owl", "wise"], category: "animals" },
  {
    emoji: "🦇",
    name: "bat",
    keywords: ["bat", "vampire"],
    category: "animals",
  },
  {
    emoji: "🐺",
    name: "wolf",
    keywords: ["wolf", "howl"],
    category: "animals",
  },
  { emoji: "🐗", name: "boar", keywords: ["boar", "pig"], category: "animals" },
  {
    emoji: "🐴",
    name: "horse face",
    keywords: ["horse", "pony"],
    category: "animals",
  },
  {
    emoji: "🦄",
    name: "unicorn",
    keywords: ["unicorn", "magical"],
    category: "animals",
  },
  {
    emoji: "🐝",
    name: "honeybee",
    keywords: ["bee", "buzz"],
    category: "animals",
  },
  {
    emoji: "🐛",
    name: "bug",
    keywords: ["bug", "insect"],
    category: "animals",
  },
  {
    emoji: "🦋",
    name: "butterfly",
    keywords: ["butterfly", "beautiful"],
    category: "animals",
  },
  {
    emoji: "🐌",
    name: "snail",
    keywords: ["snail", "slow"],
    category: "animals",
  },
  {
    emoji: "🐞",
    name: "lady beetle",
    keywords: ["ladybug", "bug"],
    category: "animals",
  },
  {
    emoji: "🐜",
    name: "ant",
    keywords: ["ant", "insect"],
    category: "animals",
  },
  {
    emoji: "🦟",
    name: "mosquito",
    keywords: ["mosquito", "bug"],
    category: "animals",
  },
  {
    emoji: "🦗",
    name: "cricket",
    keywords: ["cricket", "insect"],
    category: "animals",
  },
  {
    emoji: "🕷️",
    name: "spider",
    keywords: ["spider", "web"],
    category: "animals",
  },
  {
    emoji: "🦂",
    name: "scorpion",
    keywords: ["scorpion", "sting"],
    category: "animals",
  },
  {
    emoji: "🐢",
    name: "turtle",
    keywords: ["turtle", "slow"],
    category: "animals",
  },
  {
    emoji: "🐍",
    name: "snake",
    keywords: ["snake", "serpent"],
    category: "animals",
  },
  {
    emoji: "🦎",
    name: "lizard",
    keywords: ["lizard", "gecko"],
    category: "animals",
  },
  {
    emoji: "🐙",
    name: "octopus",
    keywords: ["octopus", "tentacles"],
    category: "animals",
  },
  {
    emoji: "🦑",
    name: "squid",
    keywords: ["squid", "tentacles"],
    category: "animals",
  },
  {
    emoji: "🦐",
    name: "shrimp",
    keywords: ["shrimp", "seafood"],
    category: "animals",
  },
  {
    emoji: "🦞",
    name: "lobster",
    keywords: ["lobster", "seafood"],
    category: "animals",
  },
  {
    emoji: "🦀",
    name: "crab",
    keywords: ["crab", "seafood"],
    category: "animals",
  },
  {
    emoji: "🐡",
    name: "blowfish",
    keywords: ["blowfish", "fish"],
    category: "animals",
  },
  {
    emoji: "🐠",
    name: "tropical fish",
    keywords: ["fish", "tropical"],
    category: "animals",
  },
  { emoji: "🐟", name: "fish", keywords: ["fish"], category: "animals" },
  {
    emoji: "🐬",
    name: "dolphin",
    keywords: ["dolphin", "smart"],
    category: "animals",
  },
  {
    emoji: "🐳",
    name: "spouting whale",
    keywords: ["whale", "spout"],
    category: "animals",
  },
  {
    emoji: "🐋",
    name: "whale",
    keywords: ["whale", "big"],
    category: "animals",
  },
  {
    emoji: "🦈",
    name: "shark",
    keywords: ["shark", "dangerous"],
    category: "animals",
  },

  // Food & Drink
  {
    emoji: "🍏",
    name: "green apple",
    keywords: ["apple", "green", "fruit"],
    category: "food",
  },
  {
    emoji: "🍎",
    name: "red apple",
    keywords: ["apple", "red", "fruit"],
    category: "food",
  },
  { emoji: "🍐", name: "pear", keywords: ["pear", "fruit"], category: "food" },
  {
    emoji: "🍊",
    name: "tangerine",
    keywords: ["orange", "tangerine", "fruit"],
    category: "food",
  },
  {
    emoji: "🍋",
    name: "lemon",
    keywords: ["lemon", "sour", "fruit"],
    category: "food",
  },
  {
    emoji: "🍌",
    name: "banana",
    keywords: ["banana", "fruit"],
    category: "food",
  },
  {
    emoji: "🍉",
    name: "watermelon",
    keywords: ["watermelon", "fruit"],
    category: "food",
  },
  {
    emoji: "🍇",
    name: "grapes",
    keywords: ["grapes", "fruit"],
    category: "food",
  },
  {
    emoji: "🍓",
    name: "strawberry",
    keywords: ["strawberry", "fruit"],
    category: "food",
  },
  {
    emoji: "🫐",
    name: "blueberries",
    keywords: ["blueberries", "fruit"],
    category: "food",
  },
  {
    emoji: "🍈",
    name: "melon",
    keywords: ["melon", "fruit"],
    category: "food",
  },
  {
    emoji: "🍒",
    name: "cherries",
    keywords: ["cherry", "fruit"],
    category: "food",
  },
  {
    emoji: "🍑",
    name: "peach",
    keywords: ["peach", "fruit"],
    category: "food",
  },
  {
    emoji: "🥭",
    name: "mango",
    keywords: ["mango", "fruit"],
    category: "food",
  },
  {
    emoji: "🍍",
    name: "pineapple",
    keywords: ["pineapple", "fruit"],
    category: "food",
  },
  {
    emoji: "🥥",
    name: "coconut",
    keywords: ["coconut", "fruit"],
    category: "food",
  },
  {
    emoji: "🥝",
    name: "kiwi fruit",
    keywords: ["kiwi", "fruit"],
    category: "food",
  },
  {
    emoji: "🍅",
    name: "tomato",
    keywords: ["tomato", "vegetable"],
    category: "food",
  },
  {
    emoji: "🍆",
    name: "eggplant",
    keywords: ["eggplant", "vegetable"],
    category: "food",
  },
  {
    emoji: "🥑",
    name: "avocado",
    keywords: ["avocado", "fruit"],
    category: "food",
  },
  {
    emoji: "🥦",
    name: "broccoli",
    keywords: ["broccoli", "vegetable"],
    category: "food",
  },
  {
    emoji: "🥬",
    name: "leafy greens",
    keywords: ["lettuce", "greens", "vegetable"],
    category: "food",
  },
  {
    emoji: "🥒",
    name: "cucumber",
    keywords: ["cucumber", "vegetable"],
    category: "food",
  },
  {
    emoji: "🌶️",
    name: "hot pepper",
    keywords: ["pepper", "hot", "spicy"],
    category: "food",
  },
  {
    emoji: "🫑",
    name: "bell pepper",
    keywords: ["pepper", "bell", "vegetable"],
    category: "food",
  },
  {
    emoji: "🌽",
    name: "ear of corn",
    keywords: ["corn", "vegetable"],
    category: "food",
  },
  {
    emoji: "🥕",
    name: "carrot",
    keywords: ["carrot", "vegetable"],
    category: "food",
  },
  {
    emoji: "🫒",
    name: "olive",
    keywords: ["olive", "fruit"],
    category: "food",
  },
  {
    emoji: "🧄",
    name: "garlic",
    keywords: ["garlic", "vegetable"],
    category: "food",
  },
  {
    emoji: "🧅",
    name: "onion",
    keywords: ["onion", "vegetable"],
    category: "food",
  },
  {
    emoji: "🥔",
    name: "potato",
    keywords: ["potato", "vegetable"],
    category: "food",
  },
  {
    emoji: "🍠",
    name: "roasted sweet potato",
    keywords: ["sweet", "potato", "vegetable"],
    category: "food",
  },
  {
    emoji: "🥐",
    name: "croissant",
    keywords: ["croissant", "bread"],
    category: "food",
  },
  {
    emoji: "🥖",
    name: "baguette bread",
    keywords: ["baguette", "bread"],
    category: "food",
  },
  { emoji: "🍞", name: "bread", keywords: ["bread", "loaf"], category: "food" },
  {
    emoji: "🥨",
    name: "pretzel",
    keywords: ["pretzel", "snack"],
    category: "food",
  },
  {
    emoji: "🥯",
    name: "bagel",
    keywords: ["bagel", "bread"],
    category: "food",
  },
  {
    emoji: "🥞",
    name: "pancakes",
    keywords: ["pancakes", "breakfast"],
    category: "food",
  },
  {
    emoji: "🧇",
    name: "waffle",
    keywords: ["waffle", "breakfast"],
    category: "food",
  },
  {
    emoji: "🧀",
    name: "cheese wedge",
    keywords: ["cheese", "dairy"],
    category: "food",
  },
  {
    emoji: "🍖",
    name: "meat on bone",
    keywords: ["meat", "bone"],
    category: "food",
  },
  {
    emoji: "🍗",
    name: "poultry leg",
    keywords: ["chicken", "leg", "meat"],
    category: "food",
  },
  {
    emoji: "🥩",
    name: "cut of meat",
    keywords: ["meat", "steak"],
    category: "food",
  },
  { emoji: "🥓", name: "bacon", keywords: ["bacon", "meat"], category: "food" },
  {
    emoji: "🍔",
    name: "hamburger",
    keywords: ["burger", "hamburger"],
    category: "food",
  },
  {
    emoji: "🍟",
    name: "french fries",
    keywords: ["fries", "potato"],
    category: "food",
  },
  {
    emoji: "🍕",
    name: "pizza",
    keywords: ["pizza", "slice"],
    category: "food",
  },
  {
    emoji: "🌭",
    name: "hot dog",
    keywords: ["hot", "dog", "sausage"],
    category: "food",
  },
  {
    emoji: "🥪",
    name: "sandwich",
    keywords: ["sandwich", "sub"],
    category: "food",
  },
  {
    emoji: "🌮",
    name: "taco",
    keywords: ["taco", "mexican"],
    category: "food",
  },
  {
    emoji: "🌯",
    name: "burrito",
    keywords: ["burrito", "wrap"],
    category: "food",
  },
  {
    emoji: "🫔",
    name: "tamale",
    keywords: ["tamale", "mexican"],
    category: "food",
  },
  {
    emoji: "🥙",
    name: "stuffed flatbread",
    keywords: ["falafel", "pita"],
    category: "food",
  },
  {
    emoji: "🧆",
    name: "falafel",
    keywords: ["falafel", "chickpea"],
    category: "food",
  },
  { emoji: "🥚", name: "egg", keywords: ["egg", "protein"], category: "food" },
  {
    emoji: "🍳",
    name: "cooking",
    keywords: ["cooking", "egg", "fry"],
    category: "food",
  },
  {
    emoji: "🥘",
    name: "shallow pan of food",
    keywords: ["paella", "pan"],
    category: "food",
  },
  {
    emoji: "🍲",
    name: "pot of food",
    keywords: ["pot", "stew"],
    category: "food",
  },
  {
    emoji: "🫕",
    name: "fondue",
    keywords: ["fondue", "cheese"],
    category: "food",
  },
  {
    emoji: "🥣",
    name: "bowl with spoon",
    keywords: ["bowl", "cereal"],
    category: "food",
  },
  {
    emoji: "🥗",
    name: "green salad",
    keywords: ["salad", "healthy"],
    category: "food",
  },
  {
    emoji: "🍿",
    name: "popcorn",
    keywords: ["popcorn", "movie"],
    category: "food",
  },
  {
    emoji: "🧈",
    name: "butter",
    keywords: ["butter", "dairy"],
    category: "food",
  },
  {
    emoji: "🧂",
    name: "salt",
    keywords: ["salt", "seasoning"],
    category: "food",
  },
  {
    emoji: "🥫",
    name: "canned food",
    keywords: ["can", "soup"],
    category: "food",
  },

  // Activities & Sports
  {
    emoji: "⚽",
    name: "soccer ball",
    keywords: ["soccer", "football", "ball"],
    category: "activities",
  },
  {
    emoji: "🏀",
    name: "basketball",
    keywords: ["basketball", "ball"],
    category: "activities",
  },
  {
    emoji: "🏈",
    name: "american football",
    keywords: ["football", "american", "ball"],
    category: "activities",
  },
  {
    emoji: "⚾",
    name: "baseball",
    keywords: ["baseball", "ball"],
    category: "activities",
  },
  {
    emoji: "🥎",
    name: "softball",
    keywords: ["softball", "ball"],
    category: "activities",
  },
  {
    emoji: "🎾",
    name: "tennis",
    keywords: ["tennis", "ball"],
    category: "activities",
  },
  {
    emoji: "🏐",
    name: "volleyball",
    keywords: ["volleyball", "ball"],
    category: "activities",
  },
  {
    emoji: "🏉",
    name: "rugby football",
    keywords: ["rugby", "ball"],
    category: "activities",
  },
  {
    emoji: "🥏",
    name: "flying disc",
    keywords: ["frisbee", "disc"],
    category: "activities",
  },
  {
    emoji: "🎱",
    name: "pool 8 ball",
    keywords: ["pool", "8", "ball"],
    category: "activities",
  },
  {
    emoji: "🪀",
    name: "yo-yo",
    keywords: ["yo-yo", "toy"],
    category: "activities",
  },
  {
    emoji: "🏓",
    name: "ping pong",
    keywords: ["ping", "pong", "table", "tennis"],
    category: "activities",
  },
  {
    emoji: "🏸",
    name: "badminton",
    keywords: ["badminton", "racket"],
    category: "activities",
  },
  {
    emoji: "🏒",
    name: "ice hockey",
    keywords: ["hockey", "ice", "stick"],
    category: "activities",
  },
  {
    emoji: "🏑",
    name: "field hockey",
    keywords: ["hockey", "field", "stick"],
    category: "activities",
  },
  {
    emoji: "🥍",
    name: "lacrosse",
    keywords: ["lacrosse", "stick"],
    category: "activities",
  },
  {
    emoji: "🏏",
    name: "cricket game",
    keywords: ["cricket", "bat"],
    category: "activities",
  },
  {
    emoji: "🥅",
    name: "goal net",
    keywords: ["goal", "net", "soccer"],
    category: "activities",
  },
  {
    emoji: "⛳",
    name: "flag in hole",
    keywords: ["golf", "flag", "hole"],
    category: "activities",
  },
  {
    emoji: "🪁",
    name: "kite",
    keywords: ["kite", "fly"],
    category: "activities",
  },
  {
    emoji: "🏹",
    name: "bow and arrow",
    keywords: ["bow", "arrow", "archery"],
    category: "activities",
  },
  {
    emoji: "🎣",
    name: "fishing pole",
    keywords: ["fishing", "pole"],
    category: "activities",
  },
  {
    emoji: "🤿",
    name: "diving mask",
    keywords: ["diving", "mask", "snorkel"],
    category: "activities",
  },
  {
    emoji: "🥊",
    name: "boxing glove",
    keywords: ["boxing", "glove"],
    category: "activities",
  },
  {
    emoji: "🥋",
    name: "martial arts uniform",
    keywords: ["martial", "arts", "karate"],
    category: "activities",
  },
  {
    emoji: "🎽",
    name: "running shirt",
    keywords: ["running", "shirt", "marathon"],
    category: "activities",
  },
  {
    emoji: "🛹",
    name: "skateboard",
    keywords: ["skateboard", "skate"],
    category: "activities",
  },
  {
    emoji: "🛼",
    name: "roller skate",
    keywords: ["roller", "skate"],
    category: "activities",
  },
  {
    emoji: "🛷",
    name: "sled",
    keywords: ["sled", "snow"],
    category: "activities",
  },
  {
    emoji: "⛷️",
    name: "skier",
    keywords: ["ski", "skiing", "snow"],
    category: "activities",
  },
  {
    emoji: "🏂",
    name: "snowboarder",
    keywords: ["snowboard", "snow"],
    category: "activities",
  },
  {
    emoji: "🪂",
    name: "parachute",
    keywords: ["parachute", "skydiving"],
    category: "activities",
  },
  {
    emoji: "🏋️",
    name: "person lifting weights",
    keywords: ["weightlifting", "gym"],
    category: "activities",
  },
  {
    emoji: "🤸",
    name: "person cartwheeling",
    keywords: ["cartwheel", "gymnastics"],
    category: "activities",
  },
  {
    emoji: "🤼",
    name: "people wrestling",
    keywords: ["wrestling", "fight"],
    category: "activities",
  },
  {
    emoji: "🤽",
    name: "person playing water polo",
    keywords: ["water", "polo"],
    category: "activities",
  },
  {
    emoji: "🤾",
    name: "person playing handball",
    keywords: ["handball", "ball"],
    category: "activities",
  },
  {
    emoji: "🤹",
    name: "person juggling",
    keywords: ["juggling", "balls"],
    category: "activities",
  },
  {
    emoji: "🧘",
    name: "person in lotus position",
    keywords: ["yoga", "meditation", "zen"],
    category: "activities",
  },
  {
    emoji: "🛀",
    name: "person taking bath",
    keywords: ["bath", "bathtub"],
    category: "activities",
  },
  {
    emoji: "🛌",
    name: "person in bed",
    keywords: ["bed", "sleep"],
    category: "activities",
  },

  // Travel & Places
  {
    emoji: "🚗",
    name: "automobile",
    keywords: ["car", "vehicle"],
    category: "travel",
  },
  { emoji: "🚕", name: "taxi", keywords: ["taxi", "cab"], category: "travel" },
  {
    emoji: "🚙",
    name: "sport utility vehicle",
    keywords: ["suv", "car"],
    category: "travel",
  },
  { emoji: "🚌", name: "bus", keywords: ["bus", "public"], category: "travel" },
  {
    emoji: "🚎",
    name: "trolleybus",
    keywords: ["trolley", "bus"],
    category: "travel",
  },
  {
    emoji: "🏎️",
    name: "racing car",
    keywords: ["racing", "car", "fast"],
    category: "travel",
  },
  {
    emoji: "🚓",
    name: "police car",
    keywords: ["police", "car"],
    category: "travel",
  },
  {
    emoji: "🚑",
    name: "ambulance",
    keywords: ["ambulance", "emergency"],
    category: "travel",
  },
  {
    emoji: "🚒",
    name: "fire engine",
    keywords: ["fire", "truck"],
    category: "travel",
  },
  {
    emoji: "🚐",
    name: "minibus",
    keywords: ["minibus", "van"],
    category: "travel",
  },
  {
    emoji: "🛻",
    name: "pickup truck",
    keywords: ["pickup", "truck"],
    category: "travel",
  },
  {
    emoji: "🚚",
    name: "delivery truck",
    keywords: ["delivery", "truck"],
    category: "travel",
  },
  {
    emoji: "🚛",
    name: "articulated lorry",
    keywords: ["truck", "lorry"],
    category: "travel",
  },
  {
    emoji: "🚜",
    name: "tractor",
    keywords: ["tractor", "farm"],
    category: "travel",
  },
  {
    emoji: "🏍️",
    name: "motorcycle",
    keywords: ["motorcycle", "bike"],
    category: "travel",
  },
  {
    emoji: "🛵",
    name: "motor scooter",
    keywords: ["scooter", "moped"],
    category: "travel",
  },
  {
    emoji: "🚲",
    name: "bicycle",
    keywords: ["bicycle", "bike"],
    category: "travel",
  },
  {
    emoji: "🛴",
    name: "kick scooter",
    keywords: ["scooter", "kick"],
    category: "travel",
  },
  {
    emoji: "🚁",
    name: "helicopter",
    keywords: ["helicopter", "chopper"],
    category: "travel",
  },
  {
    emoji: "✈️",
    name: "airplane",
    keywords: ["airplane", "plane", "flight"],
    category: "travel",
  },
  {
    emoji: "🛩️",
    name: "small airplane",
    keywords: ["small", "airplane"],
    category: "travel",
  },
  {
    emoji: "🛫",
    name: "airplane departure",
    keywords: ["departure", "takeoff"],
    category: "travel",
  },
  {
    emoji: "🛬",
    name: "airplane arrival",
    keywords: ["arrival", "landing"],
    category: "travel",
  },
  {
    emoji: "🪂",
    name: "parachute",
    keywords: ["parachute", "skydiving"],
    category: "travel",
  },
  {
    emoji: "💺",
    name: "seat",
    keywords: ["seat", "airplane"],
    category: "travel",
  },
  {
    emoji: "🚀",
    name: "rocket",
    keywords: ["rocket", "space"],
    category: "travel",
  },
  {
    emoji: "🛸",
    name: "flying saucer",
    keywords: ["ufo", "alien"],
    category: "travel",
  },
  {
    emoji: "🚉",
    name: "station",
    keywords: ["station", "train"],
    category: "travel",
  },
  {
    emoji: "🚞",
    name: "mountain railway",
    keywords: ["mountain", "railway"],
    category: "travel",
  },
  {
    emoji: "🚝",
    name: "monorail",
    keywords: ["monorail", "train"],
    category: "travel",
  },
  {
    emoji: "🚄",
    name: "high-speed train",
    keywords: ["high", "speed", "train"],
    category: "travel",
  },
  {
    emoji: "🚅",
    name: "bullet train",
    keywords: ["bullet", "train"],
    category: "travel",
  },
  {
    emoji: "🚈",
    name: "light rail",
    keywords: ["light", "rail"],
    category: "travel",
  },
  {
    emoji: "🚂",
    name: "locomotive",
    keywords: ["locomotive", "train"],
    category: "travel",
  },
  {
    emoji: "🚃",
    name: "railway car",
    keywords: ["railway", "car"],
    category: "travel",
  },
  {
    emoji: "🚋",
    name: "tram car",
    keywords: ["tram", "streetcar"],
    category: "travel",
  },
  {
    emoji: "🚇",
    name: "metro",
    keywords: ["metro", "subway"],
    category: "travel",
  },
  { emoji: "🚊", name: "tram", keywords: ["tram"], category: "travel" },
  { emoji: "🚆", name: "train", keywords: ["train"], category: "travel" },

  // Objects
  {
    emoji: "📱",
    name: "mobile phone",
    keywords: ["phone", "mobile", "cell"],
    category: "objects",
  },
  {
    emoji: "📲",
    name: "mobile phone with arrow",
    keywords: ["phone", "call", "incoming"],
    category: "objects",
  },
  {
    emoji: "☎️",
    name: "telephone",
    keywords: ["telephone", "phone"],
    category: "objects",
  },
  {
    emoji: "📞",
    name: "telephone receiver",
    keywords: ["phone", "receiver"],
    category: "objects",
  },
  {
    emoji: "📟",
    name: "pager",
    keywords: ["pager", "beeper"],
    category: "objects",
  },
  {
    emoji: "📠",
    name: "fax machine",
    keywords: ["fax", "machine"],
    category: "objects",
  },
  {
    emoji: "🔋",
    name: "battery",
    keywords: ["battery", "power"],
    category: "objects",
  },
  {
    emoji: "🪫",
    name: "low battery",
    keywords: ["battery", "low", "power"],
    category: "objects",
  },
  {
    emoji: "🔌",
    name: "electric plug",
    keywords: ["plug", "electric"],
    category: "objects",
  },
  {
    emoji: "💻",
    name: "laptop",
    keywords: ["laptop", "computer"],
    category: "objects",
  },
  {
    emoji: "🖥️",
    name: "desktop computer",
    keywords: ["desktop", "computer"],
    category: "objects",
  },
  {
    emoji: "🖨️",
    name: "printer",
    keywords: ["printer", "print"],
    category: "objects",
  },
  {
    emoji: "⌨️",
    name: "keyboard",
    keywords: ["keyboard", "type"],
    category: "objects",
  },
  {
    emoji: "🖱️",
    name: "computer mouse",
    keywords: ["mouse", "computer"],
    category: "objects",
  },
  {
    emoji: "🖲️",
    name: "trackball",
    keywords: ["trackball", "mouse"],
    category: "objects",
  },
  {
    emoji: "💽",
    name: "computer disk",
    keywords: ["disk", "minidisc"],
    category: "objects",
  },
  {
    emoji: "💾",
    name: "floppy disk",
    keywords: ["floppy", "disk", "save"],
    category: "objects",
  },
  {
    emoji: "💿",
    name: "optical disk",
    keywords: ["cd", "disk"],
    category: "objects",
  },
  { emoji: "📀", name: "dvd", keywords: ["dvd", "disk"], category: "objects" },
  {
    emoji: "🧮",
    name: "abacus",
    keywords: ["abacus", "calculate"],
    category: "objects",
  },
  {
    emoji: "🎬",
    name: "clapper board",
    keywords: ["movie", "film", "clapper"],
    category: "objects",
  },
  {
    emoji: "📺",
    name: "television",
    keywords: ["tv", "television"],
    category: "objects",
  },
  {
    emoji: "📻",
    name: "radio",
    keywords: ["radio", "music"],
    category: "objects",
  },
  {
    emoji: "🎙️",
    name: "studio microphone",
    keywords: ["microphone", "studio"],
    category: "objects",
  },
  {
    emoji: "🎚️",
    name: "level slider",
    keywords: ["slider", "level"],
    category: "objects",
  },
  {
    emoji: "🎛️",
    name: "control knobs",
    keywords: ["control", "knobs"],
    category: "objects",
  },
  {
    emoji: "🧭",
    name: "compass",
    keywords: ["compass", "direction"],
    category: "objects",
  },
  {
    emoji: "⏰",
    name: "alarm clock",
    keywords: ["alarm", "clock", "time"],
    category: "objects",
  },
  {
    emoji: "⏰",
    name: "watch",
    keywords: ["watch", "time"],
    category: "objects",
  },
  {
    emoji: "📡",
    name: "satellite antenna",
    keywords: ["satellite", "antenna"],
    category: "objects",
  },
  {
    emoji: "🔦",
    name: "flashlight",
    keywords: ["flashlight", "torch"],
    category: "objects",
  },
  {
    emoji: "🕯️",
    name: "candle",
    keywords: ["candle", "light"],
    category: "objects",
  },
  {
    emoji: "🪔",
    name: "diya lamp",
    keywords: ["diya", "lamp", "oil"],
    category: "objects",
  },
  {
    emoji: "💡",
    name: "light bulb",
    keywords: ["bulb", "light", "idea"],
    category: "objects",
  },
  {
    emoji: "🔌",
    name: "electric plug",
    keywords: ["plug", "electric"],
    category: "objects",
  },
  {
    emoji: "🧯",
    name: "fire extinguisher",
    keywords: ["fire", "extinguisher"],
    category: "objects",
  },
  {
    emoji: "🛢️",
    name: "oil drum",
    keywords: ["oil", "drum"],
    category: "objects",
  },
  {
    emoji: "💸",
    name: "money with wings",
    keywords: ["money", "wings", "fly"],
    category: "objects",
  },
  {
    emoji: "💵",
    name: "dollar banknote",
    keywords: ["dollar", "money"],
    category: "objects",
  },
  {
    emoji: "💴",
    name: "yen banknote",
    keywords: ["yen", "money"],
    category: "objects",
  },
  {
    emoji: "💶",
    name: "euro banknote",
    keywords: ["euro", "money"],
    category: "objects",
  },
  {
    emoji: "💷",
    name: "pound banknote",
    keywords: ["pound", "money"],
    category: "objects",
  },
  {
    emoji: "🪙",
    name: "coin",
    keywords: ["coin", "money"],
    category: "objects",
  },
  {
    emoji: "💰",
    name: "money bag",
    keywords: ["money", "bag", "dollar"],
    category: "objects",
  },
  {
    emoji: "💳",
    name: "credit card",
    keywords: ["credit", "card", "payment"],
    category: "objects",
  },
  {
    emoji: "💎",
    name: "gem stone",
    keywords: ["gem", "diamond", "jewel"],
    category: "objects",
  },

  // Symbols
  {
    emoji: "❤️",
    name: "red heart",
    keywords: ["love", "heart", "red"],
    category: "symbols",
  },
  {
    emoji: "🧡",
    name: "orange heart",
    keywords: ["love", "heart", "orange"],
    category: "symbols",
  },
  {
    emoji: "💛",
    name: "yellow heart",
    keywords: ["love", "heart", "yellow"],
    category: "symbols",
  },
  {
    emoji: "💚",
    name: "green heart",
    keywords: ["love", "heart", "green"],
    category: "symbols",
  },
  {
    emoji: "💙",
    name: "blue heart",
    keywords: ["love", "heart", "blue"],
    category: "symbols",
  },
  {
    emoji: "💜",
    name: "purple heart",
    keywords: ["love", "heart", "purple"],
    category: "symbols",
  },
  {
    emoji: "🖤",
    name: "black heart",
    keywords: ["love", "heart", "black"],
    category: "symbols",
  },
  {
    emoji: "🤍",
    name: "white heart",
    keywords: ["love", "heart", "white"],
    category: "symbols",
  },
  {
    emoji: "🤎",
    name: "brown heart",
    keywords: ["love", "heart", "brown"],
    category: "symbols",
  },
  {
    emoji: "💔",
    name: "broken heart",
    keywords: ["broken", "heart", "sad"],
    category: "symbols",
  },
  {
    emoji: "❣️",
    name: "heart exclamation",
    keywords: ["heart", "exclamation"],
    category: "symbols",
  },
  {
    emoji: "💕",
    name: "two hearts",
    keywords: ["two", "hearts", "love"],
    category: "symbols",
  },
  {
    emoji: "💞",
    name: "revolving hearts",
    keywords: ["revolving", "hearts"],
    category: "symbols",
  },
  {
    emoji: "💓",
    name: "beating heart",
    keywords: ["beating", "heart"],
    category: "symbols",
  },
  {
    emoji: "💗",
    name: "growing heart",
    keywords: ["growing", "heart"],
    category: "symbols",
  },
  {
    emoji: "💖",
    name: "sparkling heart",
    keywords: ["sparkling", "heart"],
    category: "symbols",
  },
  {
    emoji: "💘",
    name: "heart with arrow",
    keywords: ["heart", "arrow", "cupid"],
    category: "symbols",
  },
  {
    emoji: "💝",
    name: "heart with ribbon",
    keywords: ["heart", "ribbon", "gift"],
    category: "symbols",
  },
  {
    emoji: "💟",
    name: "heart decoration",
    keywords: ["heart", "decoration"],
    category: "symbols",
  },
  {
    emoji: "☮️",
    name: "peace symbol",
    keywords: ["peace", "symbol"],
    category: "symbols",
  },
  {
    emoji: "✝️",
    name: "latin cross",
    keywords: ["cross", "christian"],
    category: "symbols",
  },
  {
    emoji: "☪️",
    name: "star and crescent",
    keywords: ["star", "crescent", "islam"],
    category: "symbols",
  },
  {
    emoji: "🕉️",
    name: "om",
    keywords: ["om", "hinduism"],
    category: "symbols",
  },
  {
    emoji: "☸️",
    name: "wheel of dharma",
    keywords: ["wheel", "dharma", "buddhism"],
    category: "symbols",
  },
  {
    emoji: "✡️",
    name: "star of david",
    keywords: ["star", "david", "judaism"],
    category: "symbols",
  },
  {
    emoji: "🔯",
    name: "dotted six-pointed star",
    keywords: ["star", "six", "pointed"],
    category: "symbols",
  },
  {
    emoji: "🕎",
    name: "menorah",
    keywords: ["menorah", "judaism"],
    category: "symbols",
  },
  {
    emoji: "☯️",
    name: "yin yang",
    keywords: ["yin", "yang", "balance"],
    category: "symbols",
  },
  {
    emoji: "☦️",
    name: "orthodox cross",
    keywords: ["orthodox", "cross"],
    category: "symbols",
  },
  {
    emoji: "🛐",
    name: "place of worship",
    keywords: ["worship", "religion"],
    category: "symbols",
  },
  {
    emoji: "⛎",
    name: "ophiuchus",
    keywords: ["ophiuchus", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♈",
    name: "aries",
    keywords: ["aries", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♉",
    name: "taurus",
    keywords: ["taurus", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♊",
    name: "gemini",
    keywords: ["gemini", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♋",
    name: "cancer",
    keywords: ["cancer", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♌",
    name: "leo",
    keywords: ["leo", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♍",
    name: "virgo",
    keywords: ["virgo", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♎",
    name: "libra",
    keywords: ["libra", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♏",
    name: "scorpio",
    keywords: ["scorpio", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♐",
    name: "sagittarius",
    keywords: ["sagittarius", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♑",
    name: "capricorn",
    keywords: ["capricorn", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♒",
    name: "aquarius",
    keywords: ["aquarius", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "♓",
    name: "pisces",
    keywords: ["pisces", "zodiac"],
    category: "symbols",
  },
  {
    emoji: "🆔",
    name: "ID button",
    keywords: ["id", "identity"],
    category: "symbols",
  },
  {
    emoji: "⚡",
    name: "high voltage",
    keywords: ["lightning", "electric", "power"],
    category: "symbols",
  },
  {
    emoji: "🔥",
    name: "fire",
    keywords: ["fire", "hot", "flame"],
    category: "symbols",
  },
  {
    emoji: "💯",
    name: "hundred points",
    keywords: ["hundred", "100", "perfect"],
    category: "symbols",
  },
  {
    emoji: "✅",
    name: "check mark button",
    keywords: ["check", "mark", "yes"],
    category: "symbols",
  },
  {
    emoji: "☑️",
    name: "check box with check",
    keywords: ["check", "box", "done"],
    category: "symbols",
  },
  {
    emoji: "✔️",
    name: "check mark",
    keywords: ["check", "mark", "correct"],
    category: "symbols",
  },
  {
    emoji: "❌",
    name: "cross mark",
    keywords: ["cross", "mark", "no", "x"],
    category: "symbols",
  },
  {
    emoji: "❎",
    name: "cross mark button",
    keywords: ["cross", "mark", "x"],
    category: "symbols",
  },
  {
    emoji: "➕",
    name: "plus",
    keywords: ["plus", "add", "+"],
    category: "symbols",
  },
  {
    emoji: "➖",
    name: "minus",
    keywords: ["minus", "subtract", "-"],
    category: "symbols",
  },
  {
    emoji: "➗",
    name: "divide",
    keywords: ["divide", "division", "÷"],
    category: "symbols",
  },
  {
    emoji: "✖️",
    name: "multiply",
    keywords: ["multiply", "times", "×"],
    category: "symbols",
  },
  {
    emoji: "♾️",
    name: "infinity",
    keywords: ["infinity", "endless"],
    category: "symbols",
  },
  {
    emoji: "‼️",
    name: "double exclamation mark",
    keywords: ["exclamation", "double", "!!"],
    category: "symbols",
  },
  {
    emoji: "⁉️",
    name: "exclamation question mark",
    keywords: ["exclamation", "question", "!?"],
    category: "symbols",
  },
  {
    emoji: "❓",
    name: "question mark",
    keywords: ["question", "mark", "?"],
    category: "symbols",
  },
  {
    emoji: "❔",
    name: "white question mark",
    keywords: ["question", "mark", "white"],
    category: "symbols",
  },
  {
    emoji: "❗",
    name: "exclamation mark",
    keywords: ["exclamation", "mark", "!"],
    category: "symbols",
  },
  {
    emoji: "❕",
    name: "white exclamation mark",
    keywords: ["exclamation", "mark", "white"],
    category: "symbols",
  },
  {
    emoji: "〰️",
    name: "wavy dash",
    keywords: ["wavy", "dash", "~"],
    category: "symbols",
  },
  {
    emoji: "💱",
    name: "currency exchange",
    keywords: ["currency", "exchange", "money"],
    category: "symbols",
  },
  {
    emoji: "💲",
    name: "heavy dollar sign",
    keywords: ["dollar", "sign", "$"],
    category: "symbols",
  },
  {
    emoji: "⚕️",
    name: "medical symbol",
    keywords: ["medical", "health", "doctor"],
    category: "symbols",
  },
  {
    emoji: "♻️",
    name: "recycling symbol",
    keywords: ["recycle", "environment"],
    category: "symbols",
  },
  {
    emoji: "⚜️",
    name: "fleur-de-lis",
    keywords: ["fleur", "de", "lis"],
    category: "symbols",
  },
  {
    emoji: "🔱",
    name: "trident emblem",
    keywords: ["trident", "emblem"],
    category: "symbols",
  },
  {
    emoji: "📛",
    name: "name badge",
    keywords: ["name", "badge"],
    category: "symbols",
  },
  {
    emoji: "🔰",
    name: "Japanese symbol for beginner",
    keywords: ["japanese", "beginner"],
    category: "symbols",
  },
  {
    emoji: "⭐",
    name: "star",
    keywords: ["star", "favorite"],
    category: "symbols",
  },
  {
    emoji: "🌟",
    name: "glowing star",
    keywords: ["star", "glowing", "shiny"],
    category: "symbols",
  },
  {
    emoji: "✨",
    name: "sparkles",
    keywords: ["sparkles", "magic", "shiny"],
    category: "symbols",
  },
  {
    emoji: "⚡",
    name: "high voltage",
    keywords: ["lightning", "electric", "power"],
    category: "symbols",
  },
  {
    emoji: "☄️",
    name: "comet",
    keywords: ["comet", "space"],
    category: "symbols",
  },
  {
    emoji: "💫",
    name: "dizzy",
    keywords: ["dizzy", "star", "sparkle"],
    category: "symbols",
  },
  {
    emoji: "⭐",
    name: "star",
    keywords: ["star", "favorite"],
    category: "symbols",
  },
];

/**
 * Search for emojis based on query
 * @param query - Search term
 * @returns Array of matching emojis
 */
export function searchEmojis(query: string): Emoji[] {
  if (!query) return emojis.slice(0, 20); // Return first 20 emojis if no query

  const searchTerm = query.toLowerCase().trim();
  const results: { emoji: Emoji; score: number }[] = [];

  emojis.forEach((emoji) => {
    let score = 0;

    // Exact name match gets highest score
    if (emoji.name === searchTerm) {
      score = 1;
    }
    // Name starts with query
    else if (emoji.name.startsWith(searchTerm)) {
      score = 2;
    }
    // Name contains query
    else if (emoji.name.includes(searchTerm)) {
      score = 3;
    }
    // Keywords exact match
    else if (emoji.keywords.includes(searchTerm)) {
      score = 4;
    }
    // Keywords start with query
    else if (emoji.keywords.some((keyword) => keyword.startsWith(searchTerm))) {
      score = 5;
    }
    // Keywords contain query
    else if (emoji.keywords.some((keyword) => keyword.includes(searchTerm))) {
      score = 6;
    }

    if (score > 0) {
      results.push({ emoji, score });
    }
  });

  // Sort by score and return emojis
  return results
    .sort((a, b) => a.score - b.score)
    .slice(0, 20) // Limit to 20 results
    .map((result) => result.emoji);
}

/**
 * Get emojis by category
 * @param category - Category name
 * @returns Array of emojis in that category
 */
export function getEmojisByCategory(category: string): Emoji[] {
  return emojis.filter((emoji) => emoji.category === category);
}

/**
 * Get all available categories
 * @returns Array of category names
 */
export function getEmojiCategories(): string[] {
  const categories = new Set(emojis.map((emoji) => emoji.category));
  return Array.from(categories);
}

/**
 * Get a random emoji
 * @returns Random emoji
 */
export function getRandomEmoji(): Emoji {
  return emojis[Math.floor(Math.random() * emojis.length)];
}

export type { Emoji };
